/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoilerPlate {
    }
    interface UseCallbackTest {
    }
    interface UseContextTest {
    }
    interface UseEffectTest {
    }
    interface UseMemoTest {
    }
    interface UseReducerTest {
    }
    interface UseRefTest {
    }
    interface UseStateTest {
    }
}
declare global {
    interface HTMLBoilerPlateElement extends Components.BoilerPlate, HTMLStencilElement {
    }
    var HTMLBoilerPlateElement: {
        prototype: HTMLBoilerPlateElement;
        new (): HTMLBoilerPlateElement;
    };
    interface HTMLUseCallbackTestElement extends Components.UseCallbackTest, HTMLStencilElement {
    }
    var HTMLUseCallbackTestElement: {
        prototype: HTMLUseCallbackTestElement;
        new (): HTMLUseCallbackTestElement;
    };
    interface HTMLUseContextTestElement extends Components.UseContextTest, HTMLStencilElement {
    }
    var HTMLUseContextTestElement: {
        prototype: HTMLUseContextTestElement;
        new (): HTMLUseContextTestElement;
    };
    interface HTMLUseEffectTestElement extends Components.UseEffectTest, HTMLStencilElement {
    }
    var HTMLUseEffectTestElement: {
        prototype: HTMLUseEffectTestElement;
        new (): HTMLUseEffectTestElement;
    };
    interface HTMLUseMemoTestElement extends Components.UseMemoTest, HTMLStencilElement {
    }
    var HTMLUseMemoTestElement: {
        prototype: HTMLUseMemoTestElement;
        new (): HTMLUseMemoTestElement;
    };
    interface HTMLUseReducerTestElement extends Components.UseReducerTest, HTMLStencilElement {
    }
    var HTMLUseReducerTestElement: {
        prototype: HTMLUseReducerTestElement;
        new (): HTMLUseReducerTestElement;
    };
    interface HTMLUseRefTestElement extends Components.UseRefTest, HTMLStencilElement {
    }
    var HTMLUseRefTestElement: {
        prototype: HTMLUseRefTestElement;
        new (): HTMLUseRefTestElement;
    };
    interface HTMLUseStateTestElement extends Components.UseStateTest, HTMLStencilElement {
    }
    var HTMLUseStateTestElement: {
        prototype: HTMLUseStateTestElement;
        new (): HTMLUseStateTestElement;
    };
    interface HTMLElementTagNameMap {
        "boiler-plate": HTMLBoilerPlateElement;
        "use-callback-test": HTMLUseCallbackTestElement;
        "use-context-test": HTMLUseContextTestElement;
        "use-effect-test": HTMLUseEffectTestElement;
        "use-memo-test": HTMLUseMemoTestElement;
        "use-reducer-test": HTMLUseReducerTestElement;
        "use-ref-test": HTMLUseRefTestElement;
        "use-state-test": HTMLUseStateTestElement;
    }
}
declare namespace LocalJSX {
    interface BoilerPlate {
    }
    interface UseCallbackTest {
    }
    interface UseContextTest {
    }
    interface UseEffectTest {
    }
    interface UseMemoTest {
    }
    interface UseReducerTest {
    }
    interface UseRefTest {
    }
    interface UseStateTest {
    }
    interface IntrinsicElements {
        "boiler-plate": BoilerPlate;
        "use-callback-test": UseCallbackTest;
        "use-context-test": UseContextTest;
        "use-effect-test": UseEffectTest;
        "use-memo-test": UseMemoTest;
        "use-reducer-test": UseReducerTest;
        "use-ref-test": UseRefTest;
        "use-state-test": UseStateTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "boiler-plate": LocalJSX.BoilerPlate & JSXBase.HTMLAttributes<HTMLBoilerPlateElement>;
            "use-callback-test": LocalJSX.UseCallbackTest & JSXBase.HTMLAttributes<HTMLUseCallbackTestElement>;
            "use-context-test": LocalJSX.UseContextTest & JSXBase.HTMLAttributes<HTMLUseContextTestElement>;
            "use-effect-test": LocalJSX.UseEffectTest & JSXBase.HTMLAttributes<HTMLUseEffectTestElement>;
            "use-memo-test": LocalJSX.UseMemoTest & JSXBase.HTMLAttributes<HTMLUseMemoTestElement>;
            "use-reducer-test": LocalJSX.UseReducerTest & JSXBase.HTMLAttributes<HTMLUseReducerTestElement>;
            "use-ref-test": LocalJSX.UseRefTest & JSXBase.HTMLAttributes<HTMLUseRefTestElement>;
            "use-state-test": LocalJSX.UseStateTest & JSXBase.HTMLAttributes<HTMLUseStateTestElement>;
        }
    }
}
