# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, async-utils]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - haunted-hooks-testing-library
          - universal-hooks
          - universal-hooks-testing-library

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - env:
        PACKAGES: haunted-hooks-testing-library universal-hooks universal-hooks-testing-library
      - run: npm install
      - run: for P in $PACKAGES; do npm -w packages/$P run build --if-present; done
      # - run: npm -w packages/univ run build --if-present
      - run: npm -w packages/${{ matrix.package }} test
